// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd_i_qo94Do5o-hMm52163ceeaYwAzfX0',
    appId: '1:21132445812:web:a91d1fe9d446e851d26921',
    messagingSenderId: '21132445812',
    projectId: 'online-shopping-app-39152',
    authDomain: 'online-shopping-app-39152.firebaseapp.com',
    storageBucket: 'online-shopping-app-39152.firebasestorage.app',
    measurementId: 'G-QBQWBED0RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ooVBscFESaWHT8jpS8JEk5Ip_EyR444',
    appId: '1:21132445812:android:ff1475749d4bcd24d26921',
    messagingSenderId: '21132445812',
    projectId: 'online-shopping-app-39152',
    storageBucket: 'online-shopping-app-39152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjNzCBdhPo-ybWA4DxC5alzgpPN87b2hw',
    appId: '1:21132445812:ios:cfef7c207d7b0579d26921',
    messagingSenderId: '21132445812',
    projectId: 'online-shopping-app-39152',
    storageBucket: 'online-shopping-app-39152.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjNzCBdhPo-ybWA4DxC5alzgpPN87b2hw',
    appId: '1:21132445812:ios:cfef7c207d7b0579d26921',
    messagingSenderId: '21132445812',
    projectId: 'online-shopping-app-39152',
    storageBucket: 'online-shopping-app-39152.firebasestorage.app',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd_i_qo94Do5o-hMm52163ceeaYwAzfX0',
    appId: '1:21132445812:web:533edfca3390e007d26921',
    messagingSenderId: '21132445812',
    projectId: 'online-shopping-app-39152',
    authDomain: 'online-shopping-app-39152.firebaseapp.com',
    storageBucket: 'online-shopping-app-39152.firebasestorage.app',
    measurementId: 'G-5HY2JQQB22',
  );

}